services:

  app:
    build:
      context: ./node
    image: donovantarsis/node-app:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db-mysql:3306 -timeout 120s docker-entrypoint.sh
    command: sh -c "npm install && node index.js"
    restart: always
    networks:
      - node-mysql
      - node-nginx
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-mysql
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: donovantarsis/nginx:prod
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: dockerize -wait tcp://app:3000 -timeout 120s nginx -g 'daemon off;'
    restart: always
    networks:
      - node-nginx
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-nginx:
    driver: bridge
  node-mysql:
    driver: bridge